### ISSUE TITLE
Capture output of $tbs->PlugIn(OPENTBS_DEBUG_XML_SHOW)?

### ISSUE THREAD

**Issue by theopensourcerer** [Skrol29/opentbs#10]
Sorry if this is a dumb question but Is there a way I can make the above _return_ the DEBUG output, rather than immediately echoing it to the caller?

I'd like to do something like this:

`$debugOutput = $tbs->PlugIn(OPENTBS_DEBUG_XML_SHOW);`

and process $debugOutput _before_ sending to the user. 

I tried but $debugOutput was always empty.

**Comment by Skrol29** [comment]
The debug output is codded with _echo_ but you can capture it using ob_get_contents().

**Comment by theopensourcerer** [comment]
@Skrol29 Thanks for the cluebat! That should do it.
