### ISSUE TITLE
How to merge 2 file?

### ISSUE THREAD

**Issue by KonesoN** [Skrol29/opentbs#11]
How to merge two docx file,and save all images and styles?

**Comment by roxblnfk** [comment]
I think this question is equivalent to the question "how to merge two HTML pages and save all images and styles?" (or a bit more complicated).

**Comment by KonesoN** [comment]
> I think this question is equivalent to the question "how to merge two HTML pages and save all images and styles?" (or a bit more complicated).

There are 2 files "*.docx"
They need to be combined into one
And save all styles and photos

For example:
$TBS->merge('file1.docx','file2.docx','output.docx')

OR
$TBS->addFile('file1.docx')
$TBS->addFile('file2.docx')
$TBS->save('output.docx')

**Comment by KonesoN** [comment]
Use PHPWord
https://github.com/PHPOffice/PHPWord/issues/1870
