### ISSUE TITLE
Multi-Lines not managed when reading ODS file 

### ISSUE THREAD

**Issue by nicohell** [Skrol29/opentbs#27]
Hi

tbs_class.php : @version 3.13.2
tbs_plugin_opentbs.php : @version 1.10.7

We use openTbs.Plugin to read ODS file in which some cells contain multi-lines of string.

To reproduce : 
In tbs_plugin_opentbs.php :: Sheet_VisitCells() 
-> log `$cell->Txt` => text where multi-lines are made by `</text:p><text:p/><text:p>`  (<text:p/> could be multiple)
-> log $val after `OpenDoc_GetCellValue()` => return only first line

Looks like `OpenDoc_GetCellValue()`  uses `text:p` to split text but in case of multi-lines it returns only the first one

We made an (ugly) override in Sheet_VisitCells()  just before `$val = $this->OpenDoc_GetCellValue($cell);` 

```
$cell->Txt = preg_replace_callback(
    '#(</text:p>)(<text:p/>)*(<text:p>)#', 
    function($matches) {
        $return = "\n";
        if (!empty($matches[2])) {
            for ($i=0; $i < substr_count($matches[0], $matches[2]); $i++) {
                $return .= "\n";
            }
        }
        return $return;
    }, 
    $cell->Txt
); 
```
Thanks 
Nicolas

**Comment by Skrol29** [comment]
Fixed since OpenTBS version 1.11.0
