### ISSUE TITLE
MergeBlock issue with .pptx

### ISSUE THREAD

**Issue by squarou** [Skrol29/opentbs#28]
Hi,

Don't know if it's a relevant issue, but I had diffculties to use $TBS->MergeBlock() in tables or textareas in Powerpoint 2016. Merging wasn't working everytime and didn't know why.
I noticed first that using tables it was working, until I changed some format thing or row/column size... wasn't ok with that.
Finally, I noticed that some ok my template codes where underlined in red for mispelling. So, deactivating the automatic spellcheker for my tables and textareas solved everything so far !

NB : A huge thanks to @Skrol29 for those amazing scripts !

**Comment by Skrol29** [comment]
Hi,

The spelling and grammar feature can split the inner XML into several parts and then corrupt the TBS fields.
This is noticed in the Ms Word demo example. But it’s true it can happens in Powerpoint.
