### ISSUE TITLE
Exchange images using MergeBlock()

### ISSUE THREAD

**Issue by Eskapone36** [Skrol29/opentbs#29]
Hi,
I am having trouble exchanging images using the MergeBlock() function.
Maybe I am not using it correct or I'm missing something, not exactly sure, please see my example below.

```
include_once('tinybutstrong/tinybutstrong/tbs_class.php');
include_once('tinybutstrong/opentbs/tbs_plugin_opentbs.php');

$tinyButStrong = new clsTinyButStrong();
$tinyButStrong->PlugIn(TBS_INSTALL, OPENTBS_PLUGIN);
$tinyButStrong->LoadTemplate("test.docx", OPENTBS_ALREADY_UTF8);
echo time() . "</br>Before:</br><textarea rows='35' cols='200'>" . $tinyButStrong->Source . "</textarea>";
$pics = [["pics" => "test.png"]];
$blockSrc = $tinyButStrong->GetBlockSource("block1");
$tinyButStrong->MergeBlock(
    "block1",
    $pics
);

echo "</br>After:</br><textarea rows='35' cols='200'>" . $tinyButStrong->Source . "</textarea>";
$tinyButStrong->Show(OPENTBS_FILE, "test.docx");
```
template.docx: [template.docx](https://github.com/Skrol29/opentbs/files/10910348/template.docx)
test.png: ![test](https://user-images.githubusercontent.com/41552540/223450533-701e1129-9293-44ec-8b3f-e57238e184dc.png)

Used versions:
php: 8.1.8
opentbs: 1.10.7

When comparing the BlockSource before and after the MergeBlock() call, you can see that tbs does not replace correct and corrupts the file contents.

Any help or conclusion is well appreciated, thanks in advance.

(works just fine with php 7.2 & opentbs 1.9.4)

**Comment by Skrol29** [comment]
You are inserting HTML contents in DOCX which is XML under the OpenXML format. This is not supposed to work.

**Comment by Eskapone36** [comment]
Hi,
thanks for your answer but inserting HTML is not what I'm doing there.
The HTML data you see in my snippet are merely debug prints to see the file contents before and after the replacement takes place.
What I am trying to replace is the content of 'block1.pics' with 'test.png'.

**Comment by Skrol29** [comment]
Hi,
You're right, I can reproduce the bug. I'm working on it...

**Comment by Skrol29** [comment]
The bug is fixed in the new release. It was a complicated bug, thank you for your patience.
