### ISSUE TITLE
Can I use sub blocks?

### ISSUE THREAD

**Issue by theopensourcerer** [Skrol29/opentbs#9]
I am trying to create a template in LibreOffice Writer that uses subblocks. I can get the first-level block working but not the second?

The data is in a php array and is in a format like this (which I took from the example in the main docs re: "Automatic subblocks". So what I want to achieve is a table with rows by "moduleName" within each row contains another table of values for the label, name and value from the fieldData array:
![Screenshot from 2020-04-22 15-37-21](https://user-images.githubusercontent.com/3414988/79995858-a9bb7780-84af-11ea-94ca-571579b1d517.png)  

I've tried various forms of the subblock template directive (I tried replacing ".val" with .label, .name and .value obviously) but can never get it to display any data in the rendered document. Here is the relevant part of the template:
![Screenshot from 2020-04-22 15-36-56](https://user-images.githubusercontent.com/3414988/79995861-aa540e00-84af-11ea-945b-7c7dcebf2ee9.png)

And this is what gets rendered:
![Screenshot from 2020-04-22 15-45-06](https://user-images.githubusercontent.com/3414988/79996452-63b2e380-84b0-11ea-813d-371f8f7bf3d1.png)

Any ideas? Thanks.

**Comment by roxblnfk** [comment]
Your subblock should be in the scope of the main block.
I assume that the output of the subblock is outside the zone of main block.

**Comment by theopensourcerer** [comment]
I've made a small change but still not getting any data rendered in the sub block:  
![Screenshot from 2020-04-22 16-07-42](https://user-images.githubusercontent.com/3414988/79999162-80044f80-84b3-11ea-8695-e73fc585c5d7.png)

**Comment by roxblnfk** [comment]
If you are sure that the subblock falls within the coverage area of ​​the parent block, then you should make sure that the marker does not contain in excess markup due to copy-paste. To do this, copy the marker text into notepad, and then copy back from there to the template. It often helped me.

**Comment by theopensourcerer** [comment]
yay!!! Thanks for that! :-D

 I'm on Linux so I put the template directives into gedit and pasted them back in.  
![Screenshot from 2020-04-22 16-21-44](https://user-images.githubusercontent.com/3414988/80000806-84ca0300-84b5-11ea-8359-8c9ff330325f.png)

**Comment by roxblnfk** [comment]
@theopensourcerer by the way, if you need some things (for example, sorting or grouping with calculations), you can watch my [fork](https://github.com/roxblnfk/tinybutstrong). There, however, the documentation and examples are very bad, but the additional functionality allows me to generate accounting documents, invoices, sort different lists without changing the php code.
